export default function Head() {
  return (
    <>
      <title>Whispers</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      {/* pwa */}
      <link rel="manifest" href="/manifest.json" />
      <link rel="apple-touch-icon" href="/whispers.png"></link>
      <meta name="theme-color" content="#fff" />
    </>
  );
}
